version: '3'
services:
  app:
    build: ./.docker
    volumes:
      - .:/usr/src/app
      - bundle:/usr/local/bundle
      - node_modules:/app/node_modules
    depends_on:
      - pg
      - cache
    environment:
      - PORT=3000
      - RAILS_DB_HOST=pg
      - RAILS_ENV=development
      - RAILS_MEMCACHED_HOST=cache
    ports:
      - 3000:3000
    links:
      - pg
    command: bundle exec puma
    entrypoint: ./.docker/entrypoint.sh
  pg:
    image: postgres
    environment:
      - POSTGRES_USER=quartieridee
      - POSTGRES_PASSWORD=7UhEIvi9wFymva3
      - POSTGRES_DB=quartieridee_development
    volumes:
      - pg-data:/var/lib/postgresql/data
  cache:
    image: memcached:1.5-alpine
    command: [ memcached, -l, '0.0.0.0', -p, '11211' ]
  ruby:
    build: .
    command: []
volumes:
  node_modules: {}
  bundle: {}
  pg-data: {}
